{% set version = "4.13.0" %}
# We need this variable here in meta.yaml, so we better set it
{% if not DO_NOT_BUILD_WITH_CXX11_ABI is defined %}
  {% set DO_NOT_BUILD_WITH_CXX11_ABI = 0 %}
{% endif %}
{% set DO_NOT_BUILD_WITH_CXX11_ABI = DO_NOT_BUILD_WITH_CXX11_ABI|int %}

package:
  name: libitk
  version: "{{version}}"

source:
  url: https://github.com/InsightSoftwareConsortium/ITK/archive/v{{version}}.tar.gz
  sha256: 37122d65b89699df33f34e0859f1e7adf5a6222060dc1c47383ff7aa4531223a

build:
    number: 1
    skip: True   # [win and py36]
    features:
    - vc9   # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]
    script_env:
    # Control building with CXX11 abi
    - DO_NOT_BUILD_WITH_CXX11_ABI  # [linux]

requirements:
  build:
    - toolchain
    - cmake    >=3.3
    - ninja
    - expat    2.1.*
    - hdf5     # [not win]
    - jpeg     9*
    - libtiff  4.0.*
    - libpng   >=1.6.27,<1.7
    - zlib     1.2.*
    - python   # [win]
    - vc 9     # [win and py27]
    - vc 10    # [win and py34]
    - vc 14    # [win and py>=35]
  run:
    - expat    2.1.*
    - hdf5     # [not win]
    - jpeg     9*
    - libtiff  4.0.*
    - libpng   >=1.6.27,<1.7
    - zlib     1.2.*
    - vc 9   # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]

test:
  requires:
    - cmake
  files:
    - example
  commands:
    - test -d $PREFIX/include/ITK*                        # [not win]
    - if not exist %LIBRARY_INC%\\ITK* exit 1             # [win]
    - itkTestDriver -- echo "Runtime ITK OK"
# make sure to pass the compatibility flag when building the test example
# otherwise it will build with the default (CXX11) abi
# -> link errors
{% if DO_NOT_BUILD_WITH_CXX11_ABI == 1 %}
    - cmake -DCMAKE_CXX_FLAGS="-D_GLIBCXX_USE_CXX11_ABI=0" -D "CMAKE_SYSTEM_PREFIX_PATH:FILEPATH=${PREFIX}" ./example  # [not win]
    - cmake --build . --config Release
{% else %}
    - cmake -D "CMAKE_SYSTEM_PREFIX_PATH:FILEPATH=${PREFIX}" ./example  # [not win]
    - cmake --build . --config Release
{% endif %}                               # [not win]

about:
  home: http://www.itk.org
  license: Apache 2.0
  license_file: LICENSE
  summary: Runtime libraries and header files for the Insight Toolkit for segmentation and registration.

extra:
    recipe-maintainers:
      - blowekamp
      - bluescarni
